### ISSUE TITLE
Keep current lang value in the local storage or cookies instead of query param

### ISSUE THREAD

**Issue by cyntler** [martinkr/next-export-i18n#19]
Like in the title of this issue. Is it possible?

**Comment by martinkr** [comment]
Hey,

The GET-Param is not the prettiest solution, I agree. 
If we keep the language only in storage/cookie, we loose the ability to link into a specific language (sharing etc).
I was thinking how to solve, but I don't have a final solution yet. 

Do you have any ideas? 

Cheers!

**Comment by cyntler** [comment]
Hey @martinkr, I see.

So here my first, initial idea is to use query param but only we want to use a link to some language.
What does it mean?

1. When the user enters the page, we check if there is a key in query params with the name of one of the languages we have in i18n.translations:
    - If so, we save the `currentLang` cookie with the value of this language.
    - If not, we save the `currentLang` cookie with the value of defaultLang, but only if the` currentLang `cookie does not exist yet.
2. All of hooks and components read the current lang from cookie.
3. LanguageSwitcher updates the value in the cookie.
4. The <Link /> component doesn't need to use `query`.

Additionaly, the next thing to change in my opinion is changing the `lang` query param to a new form.
Instead of `?lang=en` or `?lang=pl` we can only use something like `?en` or `?pl`.

What do you think?

**Comment by martinkr** [comment]
Really Appreciate your thoughts!
The outgoing links I'm mostly concerned with, someone copying from the address bar or opening in a new window (should be not a problem with the cookie) ... going to think about this tomorrow, it's late and I need to finish some papers :D

**Comment by mohammad0-0ahmad** [comment]
Hello! 
I've created a tiny package that you might want to check.
@martinkr  @cyntler 
I preferred to create a separate package in case you don't like my implementation check source code, it might be something you would like to implement in this package.
Best regards.

**Comment by mohammad0-0ahmad** [comment]
Sorry, I forgot to  provide repo link.
https://github.com/m0-0a/next-intl

**Comment by sanjanind** [comment]
@martinkr I was looking for a solution where language will be picked from preference instead of query param.
So basically, this lib is not capable of this.

**Comment by mohammad0-0ahmad** [comment]
> @martinkr I was looking for a solution where language will be picked from preference instead of query param.
> So basically, this lib is not capable of this.

Check this:
https://www.npmjs.com/package/@m0-0a/next-intl

**Comment by cyntler** [comment]
@sanjanind @mohammad0-0ahmad Or this: https://github.com/cyntler/next-locales

**Comment by martinkr** [comment]
https://github.com/martinkr/next-export-i18n/issues/51
