### ISSUE TITLE
What happens to SEO when using this package?

### ISSUE THREAD

**Issue by vincentsartoko** [martinkr/next-export-i18n#31]
May I know whether the SEO will be affected when using this package for the translation?

**Comment by martinkr** [comment]
Hi,

Thank you for taking the time to ask. It's a comprehensive question, and SEO depends on many factors. 
As it operates on next.js, a javascript-driven SPA framework, I assume that the package does not have a massive impact on the SEO scores. Most of the challenges with indexing a javascript SPA should be resolved with the framework.

But in the end, you should test it for yourself.

Cheers!
