### ISSUE TITLE
404 on reload

### ISSUE THREAD

**Issue by flrnd** [martinkr/next-export-i18n#35]
I'm having some trouble trying to fix a problem with exported sites, if you reload a page, you get a 404 from the server. Maybe I missed something during the development?

EDIT2: Removed the hydration issue, solved it on production, just trying to figure out the 404 on exported sites.

Thanks in advance!

**Comment by martinkr** [comment]
Hi @flrnd,

Thank you for reaching out. Unfortunately, I can not reproduce your issue.
For example, https://next-export-i18n-example.vercel.app/nyc?lang=en works fine for me.
You can see the source code here: https://github.com/martinkr/next-export-i18n-example

Can you send me a link to your repo or a sample site where the 404 issue appears?

Cheers!

**Comment by flrnd** [comment]
Hi @martinkr,

I don't have access to that repository anymore. Sorry for not updating this issue sooner! Closing it since I can't reproduce it either.
