### ISSUE TITLE
Support for html inside text

### ISSUE THREAD

**Issue by xkal36** [martinkr/next-export-i18n#4]
First of all, I just wanted to say thanks for putting this together!

I think it would be great if there was support for html inside text. In other words something like the `Trans` component in [`next-translate`]( https://github.com/vinissimus/next-translate#trans-component).

My use case is a long paragraph with different styling for different parts of the text. The alternative would be to just have a bunch entries in my .json translations file, instead of one for the whole paragraph.

**Comment by martinkr** [comment]
Hi, 

I don't know your use case, but maybe you can use 
```
{
	"htmlstring": "<p>my <I>italic</I> text</p>",
}
<div
                                dangerouslySetInnerHTML={{
                                    __html: t('htmlstring');
                                }}
></div>```

or a moustache template like

```
{
	"myTemplate": "{{count}} times",
}

const key = 'myTemplate';
let string = t(key, { count: 2 }))
// string will be "2 times"
```

If nothing works out for you, we can think about how to extend the package :)

Cheers!

**Comment by xkal36** [comment]
Thanks for replying so quick and for the suggestions! I can see how the first suggestion would work and guess it should be fine from a security since it's me adding the html. I will give this a go and if it doesn't work out, will maybe submit a PR  to add something like the Trans component I mentioned

**Comment by martinkr** [comment]
Yes, innerHTML, totally depends on your threat model. 
You can also think about using the translated string through something like https://github.com/cure53/DOMPurify

Cheers!

**Comment by martinkr** [comment]
Hi xkal36, 

did you solve the issues or should be take another look?

Cheers,

Martin

**Comment by xkal36** [comment]
> Hi xkal36,
> 
> did you solve the issues or should be take another look?
> 
> Cheers,
> 
> Martin

Yes that solved it. Thank you for the help!
