### ISSUE TITLE
Invalid default language 'en'

### ISSUE THREAD

**Issue by bardiahabibi** [martinkr/next-export-i18n#5]
Hi Martin
Does it work with Next 12, because I have just got this error? I don't know my mistake but all I did was exactly the same as the steps you mentioned in the library.
![Capture](https://user-images.githubusercontent.com/41470357/140621579-1fad0a27-cb31-4738-90e9-4f4409587788.JPG)

**Comment by martinkr** [comment]
Hi Bardia,

I don't assume a problem with next v12, it should work fine but I did not have time to test it.

Anyway, the error message indicates that the hook does not find  the `defautLanguage` key.

Can you verify that your `i18n/index.js` is setup correctly? It's step #3 in the README.md.

Cheers,

Martin

**Comment by bardiahabibi** [comment]
Dear Martin

It was by me. I just copy-pasted the README and forgot the "i18n" you added in the translations files.

![readme](https://user-images.githubusercontent.com/41470357/140644721-b672c3fc-f92c-4556-89a7-68c6cbd424bb.JPG)
![me](https://user-images.githubusercontent.com/41470357/140644726-24b3b3ce-d190-481f-ab18-8076b1eca0f6.JPG)

Thanks
