### ISSUE TITLE
When I try building my next.js project using 'yarn build':

### ISSUE THREAD

**Issue by mr-ezak** [martinkr/next-export-i18n#58]
Everytime I try building using the 'Yarn build' command I get the Following Error for some of my pages:
TypeError: Cannot read properties of undefined (reading 'split')
![Screen Shot 2023-04-29 at 12 59 27 AM](https://user-images.githubusercontent.com/28624243/235257430-7ff36ff7-398e-4612-8a9e-0608c5fbb1e4.png)

**Comment by martinkr** [comment]
Hi @mr-ezak,

Thank you for reaching out. I'm trying to understand your issue: are you trying to run yarn build for this repository or your project?

Cheers!

**Comment by mr-ezak** [comment]
Tnx a lot for answering, I was trying to use "yarn build" in my own project but I keep receiving errors for using the "t" function :

`
import { useTranslation } from 'next-export-i18n'
const {t} = useTranslation()
`

But then I realized that I was using the "t" function multiple times and nested which is wrong, So when I used it properly problem got solved, and "yarn build" worked perfectly.

Thanks again for such an amazing package, Keep up the good work.🫡
