### ISSUE TITLE
Support per-page JSON files

### ISSUE THREAD

**Issue by L1lith** [martinkr/next-export-i18n#6]
It would be really nifty if there was a mechanism to import the translations on a per-page basis. I would like to have one translation file associated with each page rather than one giant translation file for each language.

**Comment by martinkr** [comment]
Hi L1lith,

thank you for suggesting a new feature.

Unfortunately, `next-export-i18n` does not support a concept like namespaces spread out across different files out-of-the-box.

A possible solution would be to merge the separate `yaml`-files on build using a package such as [merge-yaml-cli](https://www.npmjs.com/package/merge-yaml-cli)

If you mind to take a look at the [example project's source code](https://github.com/martinkr/next-export-i18n-example), you will see that the build scripts in the `package.json` are converting the `yaml`-files into the required `json`-format.

```json
{
    "yaml2json": "npx yaml2json ./i18n --pretty --save --recursive",
}
```

You could do something like 
```json
{   "yamlMergeEn": "npx merge-yaml -i ./i18n/*.en.yaml -o ./i18n/translations.en.yaml",
{   "yamlMergeDe": "npx merge-yaml -i ./i18n/*.de.yaml -o ./i18n/translations.de.yaml",
    "yaml2json": " yamlMergeEn && yamlMergeDe && npx yaml2json ./i18n --pretty --save --recursive",
}
```
 
Or use their Node.js API to create a script which merge the files and then convert them from `yaml` to `json`.

Cheers,

Martin

**Comment by martinkr** [comment]
Hi L1lith,

you're good and we're closing this issue or you have some more input on this topic?

Cheers!
