### ISSUE TITLE
App router migration - Error: NextRouter was not mounted

### ISSUE THREAD

**Issue by jimmyrleung** [martinkr/next-export-i18n#66]
Hey,

We are currently migrating our Next.js application to App Router, and we are seeing the issue below.

This is probably happening because the `useTranslation` and `useSelectedLanguage` hooks use `useRouter` from `next/router`, which is not supported by the app router [as mentioned here](https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration#step-5-migrating-routing-hooks)

![image](https://github.com/martinkr/next-export-i18n/assets/22828137/570a5355-b094-4ff5-87a3-7509bd04bf9a)

Would you have any plans to migrate to using the new navigation hooks from next? 

Also, I can see that the router is even not used in the `useTranslation` hook, it could be removed, but the `useSelectedLanguage` would require an actual migration

https://github.com/martinkr/next-export-i18n/blob/main/module/src/hooks/use-translation.tsx
https://github.com/martinkr/next-export-i18n/blob/main/module/src/hooks/use-selected-language.tsx

Thanks,
Jimmy.

**Comment by martinkr** [comment]
https://www.npmjs.com/package/next-export-i18n/v/3.0.0

**Comment by jimmyrleung** [comment]
@martinkr just wanted to thank you for releasing the temporary beta version for v3, we updated it this past sprint and it worked like a charm, we'll now work to update to the stable v3, really appreciate it!

**Comment by martinkr** [comment]
Hi @jimmyrleung,

Thank you for your great contribution!
Glad to hear that the beta worked for you. If you have any issues with v3 or additional feature ideas, let me know.

Cheers!
