### ISSUE TITLE
Support SSG

### ISSUE THREAD

**Issue by L1lith** [martinkr/next-export-i18n#7]
As far as I can tell this library works entirely client side, which is a bad thing if someone is visiting and has JavaScript disabled. This is also bad because it means their initial render will be in a foreign language (I am exporting statically). It would be nice if there was an option to render to different subroutes instead like /en/ or /fr/

I'm not sure if this is already possible but it's been confusing trying to figure out how to do this on next.js in general

**Comment by martinkr** [comment]
Hi L1lith,

thank you for reaching out.

You are completely right, `next-export-i18n` requires javascript on the client side. It is build _on top_ of Next.js. Using _"different subroutes instead like /en/ or /fr/"_ can be achieved with [Next.js's out-of-the-box internationalized (i18n) routing](https://nextjs.org/docs/advanced-features/i18n-routing). But this is supported for `$ next export`.

I am not entirely sure about your use case, you are mentioning _"Server Side Rendering"_ and saying that you are _"exporting statically"_.

- If you are using one of the [Next.js's multiple methods of server-side rendering (SSR, SSG, ISG)](https://dev.to/martinkr/the-two-and-a-half-one-flavors-of-next-js-s-pre-rendering-44o), you can use an l18n library such as [https://react.i18next.com](https://react.i18next.com).
- If you are using `next export`to create a complete static version of your site which can be used without Next.js's server components, [next-export-i18n](https://www.npmjs.com/package/next-export-i18n) is a great option.

>react-i18next is optimally suited for server-side rendering

Please see my article on dev.to [The two and a half + one flavors of `Next.js`'s pre-rendering](https://dev.to/martinkr/the-two-and-a-half-one-flavors-of-next-js-s-pre-rendering-44o) for a quick guide through SSR, SSG, ISG.

 Cheers,

 Martin

**Comment by martinkr** [comment]
Hi L1lith,

you're good and we're closing this issue or you have some more input on this topic?

Cheers!
